document.write('<table id="input" border="1">')
document.write('<thead><tr>')
document.write('<th>id</th><th>SRC1</th><th>TGT1</th>')
document.write('</tr></thead>')
document.write('<tbody>')
document.write('<tr><td>1</td><td>1</td><td></td></tr>')
document.write('<tr><td>1</td><td></td><td>1</td></tr>')
document.write('</tbody></table>')
